import type { Metadata } from "next";
import "./globals.css";
import { Space_Grotesk } from "next/font/google";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const space = Space_Grotesk({ subsets: ["latin"] });



export const metadata: Metadata = {
  title: "Ctrl Developers",
  description: "Generated by create next app",
  icons:{
    icon: [
      {
        url: "favicon.png",
        href: "/favicon.png" 
      }
    ]
  }
 
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${space.className} antialiased bg-background scroll-smooth `}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
